# Training related
train: True
use_pretrained: False
draw_tsne: False
draw_force: True

n_epoch: 20
# Optimizer related
lr: 0.1  

inf_dir: inference/v3
#save 
model_dir: model.pth
log_dir: loss.csv
inf_s: s.png
inf_t: t.png
tSNE: tSNE.png

# Backbone
backbone: resnet50
# Transfer loss related
reg_weight: 1
clf_weight: 0
transfer_weight: 1
transfer_loss: lmmd

#data
src_dir: data/inpainting/train
tar_dir: data/inpainting/test
rfimage_source: data/inpainting/ref.jpg
rfimage_target: data/inpainting/ref.jpg

#inference
test_source_dir: data/inpainting/test
test_target_dir: data/inpainting/test

#tSNE
tSNE_source_dir: data/inpainting/ori
tSNE_target_dir: data/inpainting/ori

#pretrained
pretrained: inf2/inpainting/GRAM2/model_r.pth

# others
seed: 1
num_workers: 1

