train: false
use_pretrained: true
draw_tsne: true
draw_force: false
n_epoch: 10
lr: 0.01
inf_dir: inference/v3_c
model_dir: model_s.pth
log_dir: loss_s.csv
inf_s: sc2.png
inf_t: tc2.png
tSNE: tSNE_s.png
backbone: resnet50
reg_weight: 1
clf_weight: 1
transfer_weight: 0
transfer_loss: adv
src_dir: data/wmb1i1/train
tar_dir: data/mb0i0/train
rfimage_source: data/wmb1i1/ref.jpg
rfimage_target: data/mb0i0/ref.jpg
test_source_dir: data/wmb1i1/test
test_target_dir: data/mb0i0/test
tSNE_source_dir: data/wmb1i1/ori
tSNE_target_dir: data/mb0i0/ori
pretrained: inference/v3/wmb1i1/GRAM/model.pth
seed: 1
num_workers: 4
data_save: source_only
use_checkpoint: true
