# Backbone
# backbone: resnet18

# Dare
tradeoff_angle: 0.1
tradeoff_scale: 0.05
treshold: 0.9

#dir
src_dir: data/JAN16/source/train
tar_dir: data/JAN16/target/train
fp: forcePosition/force.csv
img: images
rfimage_source: data/JAN16/source/ref.jpg
rfimage_target: data/JAN16/target/ref.jpg

# Training related
test_interval: 100
num_iter: 2000
batch_size: 32

# Optimizer related
lr_backbone: 0.001
lr_reg: 0.01
weight_decay: 5e-4
momentum: 0.9
lr_scheduler: True
lr_gamma: 1e-4
lr_decay: 0.75


# Others
seed: 1
num_workers: 1
