train: false
use_pretrained: true
draw_tsne: true
draw_force: false
n_epoch: 20
lr: 0.1
inf_dir: inference/v3_2
model_dir: model.pth
log_dir: loss.csv
inf_s: s.png
inf_t: t.png
tSNE: tSNE.png
backbone: resnet50
reg_weight: 0
clf_weight: 1
transfer_weight: 0
transfer_loss: gram
src_dir: data/wmb1i1/train
tar_dir: data/wmb2i2/train
rfimage_source: data/wmb1i1/ref.jpg
rfimage_target: data/wmb2i2/ref.jpg
test_source_dir: data/wmb1i1/test
test_target_dir: data/wmb2i2/test
tSNE_source_dir: data/wmb1i1/ori
tSNE_target_dir: data/wmb2i2/ori
pretrained: inference/v3/wmb1i1/GRAM/model.pth
seed: 1
num_workers: 4
data_save: model_trans
use_checkpoint: true
